from __future__ import (absolute_import, division, print_function)

from pygdp import shapefile_value_handle


def getGMLIDs(shapefile, attribute, value, wfs_url):
    """
    This function returns the gmlID associated with a particular attribute value.
    """
    tuples = getTuples(shapefile, attribute, wfs_url)
    return _getFilterID(tuples, value)


def getTuples(shapefile, attribute, wfs_url):
    """
    Will return the dictionary tuples only.
    """
    return shapefile_value_handle.getValues(shapefile, attribute, getTuples='only', limitFeatures=None, wfs_url=wfs_url)


def _getFilterID(tuples, value):
    """
    Given a the tuples generated by getTuples and a value, will return a list of gmlIDs
    associated with the value specified.
    """
    value = str(value)
    filterID = []
    for item in tuples:
        if item[0] == value:
            filterID.append(item[1])
    if not filterID:
        raise Exception('Feature attribute value %s was not found in the feature collection.' % value)
    return filterID
